[general]
import = [ 
  "~/.config/alacritty/nordic.toml",
  "~/.config/alacritty/keybinds.toml"
]

[window]
decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape = "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
size = 16.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"
